version: '3.9'
services:

  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'

  backend:
    build: backend/.
    depends_on:
      - db
    ports:
      - '5002:80'